/**
 * Regenerate src/wasm-bytes.ts from the built Rust cdylib.
 *
 *   cd packages/rust && cargo build --release --target wasm32-unknown-unknown
 *   cd ../core-js  && node tools/embed_wasm.mjs
 *
 * The point of this script is the assertion, not the base64. The wasm this
 * package ships is the SAME binary that passed the golden-trace parity test,
 * the 10,000-tick edge soak, and every published latency figure. If a build
 * ever produces different bytes, that is a new controller and every one of
 * those receipts stops describing it. So this refuses to embed anything whose
 * SHA-256 is not the expected digest, and you have to come here and change the
 * constant deliberately, with a changelog entry, rather than discover it later.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// The controller binary, unchanged since 0.1.1 and byte-identical across the
// 1.0.1 gcc-core -> gubernaut-core rename.
const EXPECTED_SHA256 =
  "834015d73e6576d6c597b5a32a62c24ac56a50c7023261bf84b96beb01ded7d8";

const here = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(
  here, "..", "..", "rust", "target", "wasm32-unknown-unknown", "release",
  "gubernaut_core.wasm",
);

let bytes;
try {
  bytes = readFileSync(wasmPath);
} catch {
  console.error(`no wasm at ${wasmPath}\n` +
    "Build it first:\n" +
    "  cd ../rust && cargo build --release --target wasm32-unknown-unknown");
  process.exit(1);
}

const got = createHash("sha256").update(bytes).digest("hex");
if (got !== EXPECTED_SHA256) {
  console.error(
    "REFUSING TO EMBED. The wasm is not the verified controller.\n" +
    `  expected ${EXPECTED_SHA256}\n` +
    `  got      ${got}\n\n` +
    "Different bytes mean a different controller. The parity corpus, the edge\n" +
    "soak and every published latency figure describe the expected binary and\n" +
    "would no longer describe this one. If the change is intended, update\n" +
    "EXPECTED_SHA256 here, re-run the parity and soak tests, and say so in\n" +
    "CHANGELOG.md.");
  process.exit(1);
}

const b64 = bytes.toString("base64");
const out = `// GENERATED by tools/embed_wasm.mjs. Do not edit.
//
// The Gubernaut controller compiled to wasm32-unknown-unknown, base64 inlined so
// this package has no loader config, no bundler plugin, no fetch, and no
// filesystem access. That is what lets it run unchanged in Node, Deno, Bun,
// Cloudflare workerd and the browser.
//
// SHA-256 of the decoded bytes: ${EXPECTED_SHA256}
// Byte count: ${bytes.length}
//
// This is the same binary published as the \`gubernaut-core\` crate's cdylib. It
// is verified on every import by assertWasmDigest() in wasm.ts, and again at
// embed time by the script that wrote this file.

export const WASM_SHA256 = "${EXPECTED_SHA256}";
export const WASM_BYTE_LENGTH = ${bytes.length};
export const WASM_BASE64 =
  "${b64}";
`;

writeFileSync(join(here, "..", "src", "wasm-bytes.ts"), out, "utf8");
console.log(`embedded ${bytes.length} bytes, sha256 ${got.slice(0, 8)}...`);
