//! Golden-trace parity: the Rust core must reproduce the Python reference
//! value-exactly on every scenario step, and reject every boundary case.
//!
//! Traces: tests/golden/traces.jsonl (generated by
//! packages/python/tools/gen_golden_traces.py; regenerate there, never edit by hand).

use gubernaut_core::{Config, ControllerState, HomeostaticLoop, Telemetry};
use serde_json::Value;
use std::str::FromStr;

fn traces() -> Vec<Value> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/traces.jsonl");
    let text = std::fs::read_to_string(path).expect("golden traces present");
    text.lines()
        .map(|l| serde_json::from_str(l).expect("valid JSONL line"))
        .collect()
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("number")
}

#[test]
fn config_defaults_match_python_reference() {
    let cfg = Config::default();
    for line in traces() {
        if line["type"] == "config" {
            assert_eq!(cfg.retain, f(&line["retain"]));
            assert_eq!(cfg.gain, f(&line["gain"]));
            assert_eq!(cfg.decay_recovery, f(&line["decay_recovery"]));
            assert_eq!(cfg.persev_retain, f(&line["persev_retain"]));
            assert_eq!(cfg.persev_gain, f(&line["persev_gain"]));
            assert_eq!(cfg.t_inhibit, f(&line["t_inhibit"]));
            assert_eq!(cfg.t_reground, f(&line["t_reground"]));
            assert_eq!(cfg.recovery_turns, line["recovery_turns"].as_i64().unwrap());
            assert_eq!(cfg.temp_open, f(&line["temp_open"]));
            assert_eq!(cfg.temp_clamped, f(&line["temp_clamped"]));
            return;
        }
    }
    panic!("no config line in golden traces");
}

#[test]
fn scenarios_replay_value_exactly() {
    let hrl = HomeostaticLoop::default();
    let mut scenarios = 0;
    let mut steps_checked = 0;

    for line in traces() {
        if line["type"] != "scenario" {
            continue;
        }
        scenarios += 1;
        let name = line["name"].as_str().unwrap();
        let mut state = ControllerState::default();

        for (i, step) in line["steps"].as_array().unwrap().iter().enumerate() {
            let tel = &step["tel"];
            let telemetry = Telemetry::new(f(&tel[0]), f(&tel[1]), f(&tel[2]))
                .unwrap_or_else(|e| panic!("{name} step {i}: rejected valid telemetry: {e}"));
            let d = hrl.update(state, telemetry);
            state = d.state;

            let e = &step["expect"];
            assert_eq!(state.equilibrium, f(&e["equilibrium"]), "{name} step {i} equilibrium");
            assert_eq!(state.arousal, f(&e["arousal"]), "{name} step {i} arousal");
            assert_eq!(state.perseveration, f(&e["perseveration"]), "{name} step {i} perseveration");
            assert_eq!(state.recovery, e["recovery"].as_i64().unwrap(), "{name} step {i} recovery");
            assert_eq!(d.posture.as_str(), e["posture"].as_str().unwrap(), "{name} step {i} posture");
            assert_eq!(d.temperature_max, f(&e["temperature_max"]), "{name} step {i} temperature");
            steps_checked += 1;
        }
    }
    assert_eq!(scenarios, 8, "expected 8 golden scenarios");
    assert!(steps_checked >= 60, "expected a substantive step count, got {steps_checked}");
}

#[test]
fn boundary_cases_are_rejected() {
    let mut cases = 0;
    for line in traces() {
        if line["type"] != "boundary" {
            continue;
        }
        cases += 1;
        let name = line["name"].as_str().unwrap();
        let tel: Vec<f64> = line["tel_repr"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| f64::from_str(s.as_str().unwrap()).expect("parseable repr"))
            .collect();
        assert!(
            Telemetry::new(tel[0], tel[1], tel[2]).is_err(),
            "boundary case {name} must be rejected"
        );
    }
    assert_eq!(cases, 8, "expected 8 boundary cases");
}
