//! GCC deterministic meta-level controller (HRL) — token-free by construction.
//!
//! Bit-exact port of `python/gcc_proxy/hrl.py`: identical IEEE-754 f64
//! operations in the identical order, verified by the golden-trace parity test
//! (`tests/golden_parity.rs` over `tests/golden/traces.jsonl`, generated by
//! `python/tools/gen_golden_traces.py`).
//!
//! The boundary holds at the type level: `Telemetry` is constructed only
//! through `Telemetry::new`, which admits finite in-range floats and nothing
//! else. There is no code path by which text crosses into the controller.

#![deny(unsafe_code)]

use core::fmt;
use std::cell::Cell;

/// Working-default controller constants — mirror `python/gcc_proxy/config.py`.
/// Not the evaluated configuration from the validation record.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Config {
    pub retain: f64,
    pub gain: f64,
    pub decay_recovery: f64,
    pub persev_retain: f64,
    pub persev_gain: f64,
    pub t_inhibit: f64,
    pub t_reground: f64,
    pub recovery_turns: i64,
    pub temp_open: f64,
    pub temp_clamped: f64,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            retain: 0.72,
            gain: 0.55,
            decay_recovery: 0.45,
            persev_retain: 0.60,
            persev_gain: 0.45,
            t_inhibit: 0.35,
            t_reground: 0.65,
            recovery_turns: 3,
            temp_open: 1.0,
            temp_clamped: 0.3,
        }
    }
}

/// Rejection at the numeric boundary: out-of-range or non-finite input.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BoundaryError {
    pub field: &'static str,
}

impl fmt::Display for BoundaryError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} outside its finite unit range", self.field)
    }
}

impl std::error::Error for BoundaryError {}

fn finite_unit(value: f64, field: &'static str, lo: f64, hi: f64) -> Result<f64, BoundaryError> {
    if !value.is_finite() || !(lo <= value && value <= hi) {
        return Err(BoundaryError { field });
    }
    Ok(value)
}

/// What the sensing layer is allowed to say about a turn. Three numbers.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Telemetry {
    intensity: f64,
    valence: f64,
    repetition: f64,
}

impl Telemetry {
    pub fn new(intensity: f64, valence: f64, repetition: f64) -> Result<Self, BoundaryError> {
        Ok(Telemetry {
            intensity: finite_unit(intensity, "intensity", 0.0, 1.0)?,
            valence: finite_unit(valence, "valence", -1.0, 1.0)?,
            repetition: finite_unit(repetition, "repetition", 0.0, 1.0)?,
        })
    }

    pub fn intensity(&self) -> f64 {
        self.intensity
    }

    pub fn valence(&self) -> f64 {
        self.valence
    }

    pub fn repetition(&self) -> f64 {
        self.repetition
    }
}

/// Control flowing back down. The arbiter answers UNDER one of these.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Posture {
    Default,
    Inhibit,
    Reground,
}

impl Posture {
    pub fn as_str(&self) -> &'static str {
        match self {
            Posture::Default => "DEFAULT",
            Posture::Inhibit => "INHIBIT",
            Posture::Reground => "REGROUND",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ControllerState {
    pub equilibrium: f64,
    pub arousal: f64,
    pub perseveration: f64,
    pub recovery: i64,
}

impl Default for ControllerState {
    fn default() -> Self {
        ControllerState {
            equilibrium: 1.0,
            arousal: 0.0,
            perseveration: 0.0,
            recovery: 0,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Decision {
    pub posture: Posture,
    pub temperature_max: f64,
    pub recovery_window: i64,
    pub state: ControllerState,
}

/// One governed tick: Telemetry in, Decision out. Pure and replayable.
///
/// Structural lessons from the validation record, wired in exactly as in the
/// Python reference:
///   F1  only hostile-valence intensity accumulates (drive keyed by
///       max(0, -valence));
///   F3  the recovery window opens on a valence gate, not on quiet alone.
#[derive(Clone, Copy, Debug, Default)]
pub struct HomeostaticLoop {
    pub cfg: Config,
}

impl HomeostaticLoop {
    pub fn new(cfg: Config) -> Self {
        HomeostaticLoop { cfg }
    }

    pub fn update(&self, state: ControllerState, tel: Telemetry) -> Decision {
        let cfg = &self.cfg;

        let hostile_drive = tel.intensity() * f64::max(0.0, -tel.valence()); // F1 keying

        let cooling = state.recovery > 0;
        let retain = if cooling { cfg.decay_recovery } else { cfg.retain };
        let arousal = f64::min(1.0, state.arousal * retain + hostile_drive * cfg.gain);

        let persev = f64::min(
            1.0,
            state.perseveration * cfg.persev_retain + tel.repetition() * cfg.persev_gain,
        );

        // F3: closed only when valence turns cooperative while still charged.
        let recovery = if tel.valence() > 0.2 && state.arousal >= cfg.t_inhibit {
            cfg.recovery_turns
        } else {
            i64::max(0, state.recovery - 1)
        };

        let equilibrium = f64::max(0.0, 1.0 - 0.7 * arousal - 0.3 * persev);

        let (posture, temp) = if persev >= cfg.t_reground {
            (Posture::Reground, cfg.temp_clamped)
        } else if arousal >= cfg.t_inhibit {
            (Posture::Inhibit, cfg.temp_clamped)
        } else {
            (Posture::Default, cfg.temp_open)
        };

        Decision {
            posture,
            temperature_max: temp,
            recovery_window: recovery,
            state: ControllerState {
                equilibrium,
                arousal,
                perseveration: persev,
                recovery,
            },
        }
    }
}

// ---------------------------------------------------------------------------
// C ABI / wasm export surface — a thin, allocation-free FFI over `update`.
//
// The controller is stateless-by-parameter, so the shim is too: the host owns
// the four-scalar `ControllerState` and threads it in and out each tick. One
// `gcc_tick` performs a full governed tick, returns the posture code, and
// stashes the five f64 outputs in a thread-local scratch the getters read back.
// No heap, no raw pointers, and no `unsafe` block — a scalar `extern "C"` fn
// needs none, so `#![deny(unsafe_code)]` stays in force crate-wide. This is
// what makes `gcc_core.wasm` callable from a plain `WebAssembly.instantiate`
// with no wasm-bindgen glue (before this shim the cdylib exported only
// `memory`). The scratch is a per-instance single-thread cell; wasm32 is
// single-threaded so it is simply a module global.
// ---------------------------------------------------------------------------

thread_local! {
    /// [equilibrium, arousal, perseveration, recovery, temperature_max]
    static LAST: Cell<[f64; 5]> = const { Cell::new([1.0, 0.0, 0.0, 0.0, 1.0]) };
}

/// Posture codes returned by [`gcc_tick`].
pub const GCC_POSTURE_DEFAULT: i32 = 0;
pub const GCC_POSTURE_INHIBIT: i32 = 1;
pub const GCC_POSTURE_REGROUND: i32 = 2;
/// Returned by [`gcc_tick`] when telemetry is non-finite or out of unit range.
pub const GCC_BOUNDARY_REJECT: i32 = -1;

/// One governed tick over the working-default controller, callable across the C
/// ABI / from JS. Inputs: the three telemetry scalars, then the incoming
/// four-scalar `ControllerState` (recovery passed as f64). Returns the posture
/// code (or `-1` if telemetry is out of the finite unit range) and stashes the
/// new state + `temperature_max` for the `gcc_last_*` getters. Bit-identical to
/// calling [`HomeostaticLoop::update`] directly (verified in `ffi_tick_matches_update`).
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_tick(
    intensity: f64,
    valence: f64,
    repetition: f64,
    in_equilibrium: f64,
    in_arousal: f64,
    in_perseveration: f64,
    in_recovery: f64,
) -> i32 {
    let tel = match Telemetry::new(intensity, valence, repetition) {
        Ok(t) => t,
        Err(_) => return GCC_BOUNDARY_REJECT,
    };
    let state = ControllerState {
        equilibrium: in_equilibrium,
        arousal: in_arousal,
        perseveration: in_perseveration,
        recovery: in_recovery as i64,
    };
    let d = HomeostaticLoop::default().update(state, tel);
    LAST.with(|c| {
        c.set([
            d.state.equilibrium,
            d.state.arousal,
            d.state.perseveration,
            d.state.recovery as f64,
            d.temperature_max,
        ])
    });
    match d.posture {
        Posture::Default => GCC_POSTURE_DEFAULT,
        Posture::Inhibit => GCC_POSTURE_INHIBIT,
        Posture::Reground => GCC_POSTURE_REGROUND,
    }
}

/// New-state `equilibrium` from the most recent [`gcc_tick`] on this thread.
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_last_equilibrium() -> f64 {
    LAST.with(|c| c.get()[0])
}
/// New-state `arousal` from the most recent [`gcc_tick`].
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_last_arousal() -> f64 {
    LAST.with(|c| c.get()[1])
}
/// New-state `perseveration` from the most recent [`gcc_tick`].
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_last_perseveration() -> f64 {
    LAST.with(|c| c.get()[2])
}
/// New-state `recovery` window (as f64) from the most recent [`gcc_tick`].
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_last_recovery() -> f64 {
    LAST.with(|c| c.get()[3])
}
/// `temperature_max` decided by the most recent [`gcc_tick`].
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_last_temperature_max() -> f64 {
    LAST.with(|c| c.get()[4])
}

/// ABI/version probe so a host can sanity-check the module it loaded.
#[allow(unsafe_code)] // permits ONLY the #[no_mangle] export attribute below;
// this fn has no `unsafe` block and no raw-pointer work (all-scalar C ABI).
#[no_mangle]
pub extern "C" fn gcc_abi_version() -> i32 {
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_tick_is_bit_identical_to_update() {
        // calm zeros → DEFAULT, equilibrium 1.0
        assert_eq!(
            gcc_tick(0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
            GCC_POSTURE_DEFAULT
        );
        assert_eq!(gcc_last_equilibrium(), 1.0);
        assert_eq!(gcc_last_temperature_max(), 1.0);

        // boundary rejection at the FFI edge
        assert_eq!(
            gcc_tick(f64::NAN, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
            GCC_BOUNDARY_REJECT
        );

        // parity with a direct update() over a hostile tick from default state
        let hrl = HomeostaticLoop::default();
        let d = hrl.update(
            ControllerState::default(),
            Telemetry::new(0.9, -0.8, 0.5).unwrap(),
        );
        let expected = match d.posture {
            Posture::Default => 0,
            Posture::Inhibit => 1,
            Posture::Reground => 2,
        };
        assert_eq!(gcc_tick(0.9, -0.8, 0.5, 1.0, 0.0, 0.0, 0.0), expected);
        assert_eq!(gcc_last_arousal(), d.state.arousal);
        assert_eq!(gcc_last_perseveration(), d.state.perseveration);
        assert_eq!(gcc_last_recovery(), d.state.recovery as f64);
        assert_eq!(gcc_last_temperature_max(), d.temperature_max);
        assert_eq!(gcc_abi_version(), 1);
    }

    #[test]
    fn boundary_rejects_non_finite_and_out_of_range() {
        assert!(Telemetry::new(f64::NAN, 0.0, 0.0).is_err());
        assert!(Telemetry::new(0.5, f64::INFINITY, 0.0).is_err());
        assert!(Telemetry::new(1.5, 0.0, 0.0).is_err());
        assert!(Telemetry::new(0.5, -1.2, 0.0).is_err());
        assert!(Telemetry::new(0.5, 0.0, -0.1).is_err());
        assert!(Telemetry::new(1.0, -1.0, 1.0).is_ok());
    }

    #[test]
    fn calm_input_stays_default() {
        let hrl = HomeostaticLoop::default();
        let d = hrl.update(
            ControllerState::default(),
            Telemetry::new(0.0, 0.0, 0.0).unwrap(),
        );
        assert_eq!(d.posture, Posture::Default);
        assert_eq!(d.temperature_max, 1.0);
        assert_eq!(d.state.equilibrium, 1.0);
    }

    #[test]
    fn apology_does_not_charge_arousal() {
        // F1: positive-valence intensity contributes zero hostile drive.
        let hrl = HomeostaticLoop::default();
        let d = hrl.update(
            ControllerState::default(),
            Telemetry::new(1.0, 1.0, 0.0).unwrap(),
        );
        assert_eq!(d.state.arousal, 0.0);
    }
}
